name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: Fetch dependencies
        run: flutter pub get

      - name: Run analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test
